### ISSUE TITLE
World Ocean Atlas

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/IOMB-Data#1]
@weiweifu

I wanted to start getting all the ocean data conversion scripts into this repository and thought we could start with WOA, specifically temperature. My idea is if I can show you one script that does things in a good way, it will simpler to replicate for the others and we can work on them together.

I have some questions:

* I am downloading data from [here](https://www.ncei.noaa.gov/access/world-ocean-atlas-2018/bin/woa18.pl), choosing the NetCDF format, 1 degree, files from the monthly column.
* I see that there are several available decadal periods: '55-'64, '65-'74, '75-'84, '85-'94, '94-'04, '05-'17, or '81-'10. I get that we are getting an average year across these decades, but which one do we want to use? 
* Whatever one we pick, should we be comparing to a model average across the same decades?
* I also see that in the netCDF files, there is a `t_se` whose standard name is  `sea_water_temperature standard_error`. Could we use this as a measure of 'observational' uncertainty?

**Comment by weiweifu** [comment]
@nocollier 

Nate, thank you! Could we just try the decade of 94-04 as an example? 
I think you are correct that we compare model with data for the same timeframe. 
we can use 't_se' as observational uncertainty. we may not have this for other datasets, but can get some information from literature. Let's try the WOA18 first, then GLODAPv2.

**Comment by nocollier** [comment]
Under further inspection, there are some more choices. For any time period, I am seeing a few variables inside:

*  `t_an: Objectively analyzed mean fields for sea_water_temperature at standard depth levels` this is a globally defined map with all gaps in the data filled somehow
*  `t_mn: Average of all unflagged interpolated values at each standard depth level for sea_water_temperature in each grid-square which contain at least one measurement` also defined globally but appears to be a mean of all actual measurements taken, leaving cells masked if no measurements were taken. Thus there are a lot of gaps and for shorter time intervals you can see even see ship tracks.
* `t_sd: The standard deviation about the statistical mean of sea_water_temperature in each grid-square at each standard depth level` the standard deviation of the `t_mn` variable above. This means that it is only defined for grid cells where data was collected.

I had originally looked at the 1981-2010 period for which the `t_mn` and `t_sd` was pretty dense. If we did we could use the standard deviation as a measure of observational uncertainty. It made me wonder if we don't want to use this product. But as I look to the 1995-2004 period, the data is of course more sparse. 

Ultimately these are questions the ocean benchmarking community needs to address. For now I will just grab `t_an` for 1995-2004, but we can revisit this later.

**Comment by nocollier** [comment]
Ok, I have a start pushed. Take a look and see what you think:

https://github.com/rubisco-sfa/IOMB-Data/blob/main/WOA2018/convert.py

Also, were you extracting data at different depths? or were you taking an average over a depth range to compare to models? @weiweifu

**Comment by weiweifu** [comment]
@nocollier 
Nate, The script looks nice!
For wOA, I extract data at 0, 200 m and 700 m for the comparison in the IOMB paper. 
For GLODAPv2, I extract data and interpolate the the standard depths as in the WOA.

**Comment by nocollier** [comment]
Ok, so the script is updated to encode all the data from WOA. It will download it all and re-encode it. I want to do a few things here:

* I want to grab a few ocean models off ESGF and place them here on OLCF and run tests for the data as we update it.
* I need to extend ILAMB to understand the climatology bounds and compute one from model results
* I need to add something to the configure language such that we can add one entry for, say, temperature but then specify that we want it at any number of depths and this will get autogenerated. 
* I want to step through this script and explain it all to you. Would be great if you would be willing to learn and contribute some others in the same style.

**Comment by weiweifu** [comment]
@nocollier 

> Ok, so the script is updated to encode all the data from WOA. It will download it all and re-encode it. I want to do a few things here:
> 
> * I want to grab a few ocean models off ESGF and place them here on OLCF and run tests for the data as we update it.
> * I need to extend ILAMB to understand the climatology bounds and compute one from model results
This is important. Before, I had to download the required model output based on the data used.

> * I need to add something to the configure language such that we can add one entry for, say, temperature but then specify that we want it at any number of depths and this will get autogenerated.
This is cool. For the particular IOMB paper, all were hard-coded .

> * I want to step through this script and explain it all to you. Would be great if you would be willing to learn and contribute some others in the same style.
Sure, I think I can apply the script to other WOA variables. For GLODAPv2 or Argo and other products, to do this, I think the sparse data need to be first interpolated to gridded data as the WOA. We can talk about it later.

**Comment by nocollier** [comment]
I have added code to ILAMB in `nocollier/iomb-layering` which will take the following configure snippet:

```
[h1: Physical Drivers]

[h2: Temperature]
variable = "thetao"
depths = 0, 200, 700

[WOA2018]
source = "DATA/WOA2018/thetao.nc"
```

and generates 3 separate comparisons at each depth automatically. Can you @weiweifu take a look at the [results](https://www.ilamb.org/dev/IOMB/) and make sure it looks correct to you? 

If it looks ok, then I will make sure I didn't break any of ILAMB and push.

Also, note that the WOA formatting script already handles all the WOA variables.

**Comment by weiweifu** [comment]
Hi Nate

The temperature results look good to me. Thank you!

Best
Weiwei

**Comment by nocollier** [comment]
The WOA 2018 data (oxygen, nitrate, phosphate, silicate, temperature, and salinity) is encoded and available for download via:

`ilamb-fetch --remote_root https://www.ilamb.org/IOMB-Data`

Note that this version of the data includes:

* automatic download of raw files from the servers
* all layers present in the original sources, you can add `depths=0, 100, 200...` to your configure file to get comparisons at any given depth.
* reference information that gets rendered into the Data Information [tab](https://www.ilamb.org/dev/IOMB/PhysicalDrivers/Temperature700m/WOA2018/WOA2018.html#DataInformation) of the dataset pages. 
* updated units to be CF-compliant

Results may be found at:

https://www.ilamb.org/dev/IOMB/

where we will work on adding some more models for testing purposes.
