### ISSUE TITLE
Add SeaWIFS

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/IOMB-Data#3]
Jim was under the impression that chlorophyll is high at some river outlets and therefore a poor comparison to the global models. Should we try to mask out these areas?

**Comment by nocollier** [comment]
@weiweifu Do you know how to get the raw SeaWIFS data? I am seeing this:

https://oceandata.sci.gsfc.nasa.gov/api/file_search/


But the number of products are confusing. Do you know what you did?

![Image](https://github.com/rubisco-sfa/IOMB-Data/assets/1331463/2f573eeb-8f74-4101-963a-24586a7cbcc9)

Seems like it will be the same for MODIS-Aqua.

**Comment by weiweifu** [comment]
Hi Nate

I think I used the binned level3 data and generated the monthly
climatorlogy. You can find the files with similar names to
AQUA_MODIS.20030101.L3b.DAY.CHL.nc
<https://oceandata.sci.gsfc.nasa.gov/ob/getfile/AQUA_MODIS.20030101.L3b.DAY.CHL.nc>

https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-3%20Binned/Aqua-MODIS/2003/001/

I remember I downloaded all those files and generated monthly climatology
by averaging all data at a given month.

Best
Weiwei

**Comment by nocollier** [comment]
Thanks, that helped me navigate through things a bit better. I ended up finding that gridded climatologies by month are already created and automated their [download](https://github.com/rubisco-sfa/IOMB-Data/commit/58ee8c7b90a46fc5b618e91273293835c365e5a7).

One weird thing, there is no July for MODIS-Aqua and no September for SeaWIFS. Try running:

```
wget -q --post-data="results_as_file=1&sensor_id=6&dtid=1123&sdate=1997-09-04 00:00:00&edate=2010-12-11 00:00:00&subType=1&prod_id=chlor_a&resolution_id=9km&period=MC" -O - https://oceandata.sci.gsfc.nasa.gov/api/file_search

```
to get a list of files and you will find no `09` file.

**Comment by nocollier** [comment]
I also wonder what you think of comparing `log10` of chlorophyll?

**Comment by weiweifu** [comment]
Hi Nate
I compared the absolute value of chlorophyll, but I would think the bias
looks nicer if  the log10 values are compared.  I think some readers need
the comparison of direct measruements. maybe we can do both.
Best
Weiwei
