### ISSUE TITLE
Add LDEO

### ISSUE THREAD

**Issue by nocollier** [rubisco-sfa/IOMB-Data#5]
@weiweifu In your IOMB_AR6 results, we have a `sst` data product labeled LDEO which I assume is Lamont-Doherty Earth Observatory. It appears to be another shiptrack product but I am unable to locate more information about it. Can you please provide information where you obtained this data and what it is?

**Comment by nocollier** [comment]
Should [this](https://www.ncei.noaa.gov/products/optimum-interpolation-sst) rather be what we are encoding?

https://www.ncei.noaa.gov/products/optimum-interpolation-sst

**Comment by weiweifu** [comment]
I cannot remember exactly whether the LDEO data were copied from Olu or the
one I downloaded. I cannot now access the disk where I archived the data.
In the paper, I said Reynolds et al. 2002, it should be gridded data with
interpolation. Maybe the data were mistaken when I did the AR6 run. Let me
search if there is shiptrack SST data from LDEO.

**Comment by weiweifu** [comment]
https://iridl.ldeo.columbia.edu/SOURCES/.KAPLAN/.EXTENDED/.v1/

This is the updated LDEO SST product by Kaplan et al. (1998,2003). It also
appears to be a gridded product. I am not sure where the shiptrack LDEO SST
was from.

**Comment by nocollier** [comment]
Hmm, I am thinking that since we don't really know what is in IOMB_AR6, let's just skip this and open an Issue suggesting that we add sst datasets. I think there are a couple of potential ones we should include. How does that sound?

**Comment by weiweifu** [comment]
Sounds good. Let's just skip this one.
I still have the processed LDEO data in a public repository but not the
original website.
